[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false


[programs.devnet]
soldrive = "CxDoRt3Nt5z747KNW6vkVxvQQ7c2dHMmGmoWNmxejA3f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
